### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by lyxal** [cairdcoinheringaahing/CGCC-Blog-drafts#1]
Very nice

**Comment by lyxal** [comment]
This is an amazing issue

**Comment by lyxal** [comment]
This is really good

**Comment by lyxal** [comment]
Wow I just used the mobile github app like they intended

**Comment by lyxal** [comment]
Hello there

**Comment by lyxal** [comment]
Commit frickety fricks

**Comment by ErmineII** [comment]
Why are you doing this to my inbox!?

**Comment by lyxal** [comment]
because it's funny

**Comment by cairdcoinheringaahing** [comment]
I'm closing this, and it's staying closed. Anyone who reopens it will lose collaborator status

**Comment by lyxal** [comment]
Comments not equal reopen
